words = [
    "CLI",
    "EOF",
    "Rustls",
    "SPSC",
    "Swatinem",
    "TLS",
    "Tokio",
    "Tokio's",
    "backpressure",
    "clippy",
    "crypto",
    "direnv",
    "dotenv",
    "dtolnay",
    "envrc",
    "lossy",
    "nicknovitski",
    "nixbuild",
    "nixos",
    "nixpkgs",
    "oxalica",
    "pkgs",
    "rustfmt",
    "syscall",
    "xzf",
]
ignore_paths = [
    "Cargo.lock",
    "flake.lock",
]
ignore_patterns = ['\b[a-fA-F0-9]{64}\b']
