[package]
name    = "prattle-server"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace       = true
pem.workspace          = true
rcgen                  = "0.14.6"
rustls.workspace       = true
tokio.workspace        = true
tokio-rustls.workspace = true
tracing                = "0.1.44"
tracing-subscriber     = { version = "0.3.22", features = ["env-filter"] }

[dev-dependencies]
prattle-client.path = "../client"

[lints]
workspace = true
